### ISSUE TITLE
Framework changes (OI, declaration)

### ISSUE THREAD

**Issue by Edge7481** [UHSRobotics/FRC-2020#1]
Please review each problem

- OI needs to be within in **configureButtonBindings** in **RobotContainer.java**
- Should commands and subsystems be declared inline or in the constructor?
- Should physical parts be declared in Subsystem or RobotContainer?

Reference: 
https://docs.wpilib.org/en/latest/docs/software/commandbased/command-based-changes.html
https://docs.wpilib.org/en/latest/docs/software/commandbased/subsystems.html

**Comment by Ynng** [comment]
Refer to the example projects when in doubt

- Axis(joysticks) gets passed into commands as "DoubleSupplier", Buttons are assignment "whenPressed", etc in configureButtonBindings
- I might be wrong but I think we should declare them inline
- Physical parts should be declared in subsystems.
