### ISSUE TITLE
Add TOF sensor to hopper/intake to automate hopper

### ISSUE THREAD

**Issue by Ynng** [UHSRobotics/FRC-2020#12]
Balls jam so easily in the hopper when driving manually.

Information on the sensor
------

[https://www.maxbotix.com/firstrobotics](https://www.maxbotix.com/firstrobotics) (has example code, no libraries needed)

- [ ] Ask mechanical to do something like this 

![](https://cdn.discordapp.com/attachments/621579762887819284/687174046013849604/unknown.png)

**Comment by RoboticsUHS** [comment]
Please review the constants for the port and detection range

**Comment by Ynng** [comment]
Rips the sensor's broken, close for now
