### ISSUE TITLE
Weird issue with drive

### ISSUE THREAD

**Issue by Ynng** [UHSRobotics/FRC-2020#9]
Quickly moving the power joystick from rest to max would result in the drive train jittering back and forth.

**Comment by Edge7481** [comment]
Is this manual drive?

**Comment by Ynng** [comment]
yes it's a problem with manual drive

**Comment by Ynng** [comment]
Found the cause:
When accelerating from rest to full speed very fast, the voltage of the robot drops significantly, to around 8Volt, sometimes, this will result in the motors stopping. 
The motors of the drivetrain are set on brake mode for better control, this combined with the above causes the motors to suddenly lock up for short periods of time when accelerating, resulting in the jumpy movements.

This is likely not a programming problem.

This problem can be solved by reducing the speed multiplier of the drive train, which will decreade the voltage drop, fixing the problem.
60% speed multiplier is stable.
